### ISSUE TITLE
Menampilkan foto

### ISSUE THREAD

**Issue by pascalalfadian** [harrysenjaya/ScreenSaver#2]
Hi Harry,

Seingat saya, di program kamu itu tidak bisa menampilkan foto, karena dari StudentPortal kamu tidak bisa mengambil fotonya ya? Kalau dari SIAKAD bisa, dan bisakah kamu coba inject aja langsung pakai `Mahasiswa.setPhotoPath(String photoPath)` di mana `photoPath` nya itu diisi dari isi file [foto_harry.txt](https://github.com/harrysenjaya/ScreenSaver/files/6263727/foto_harry.txt) ini. Kalau berhasil kamu bisa dapatkan isi fotonya menggunakan `getPhotoImage()` yang bisa dijadikan sebagai `java.awt.BufferedImage` mestinya, dan ditampilkan ke layar.

Trims.

**Comment by harrysenjaya** [comment]
Karena dari StudentPortal nya tidak ada link fotonya Pa. Apakah maksudnya photoPath nya diisikan String yang random itu Pa? Karena di saya, isi filenya tersebut seperti terlampir. 
![image](https://user-images.githubusercontent.com/44296024/113696651-768fe980-96fc-11eb-8b8c-686c0a7ffbfd.png)

**Comment by pascalalfadian** [comment]
Iya betul. Itu tidak random, melainkan foto kamu dalam format base64. Cek https://en.wikipedia.org/wiki/Data_URI_scheme

**Comment by harrysenjaya** [comment]
Baik Pa. Sudah saya perbaiki dan sudah saya push.
