### ISSUE TITLE
Menghapus dan ignore intermediate files

### ISSUE THREAD

**Issue by pascalalfadian** [harrysenjaya/ScreenSaver#3]
Hi @harrysenjaya 

Bisakah kamu coba lakukan hal yang sama dengan yang saya lakukan di f10ab75833ec5ff43e5a581bedcc1c847a60c607 ? Jadi file2 di direktori `target/` itu merupakan "intermediate files", artinya file yang di-generate hasil kompilasi dari file2 `.java`. Kalau setiap java nya berubah, ini juga berubah, tetapi semestinya tidak masuk ke repository karena perubahannya tidak penting dan selalu bisa di-generate ulang dari java nya.

Trims.

**Comment by harrysenjaya** [comment]
Sudah saya hapus dan ignore ya Pa.
