### ISSUE TITLE
Buat satu method untuk mengupdate view

### ISSUE THREAD

**Issue by pascalalfadian** [harrysenjaya/ScreenSaver#4]
Hi @harrysenjaya 

Tolong:

1. Pull update terbaru dari saya
2. Buat satu method di `PrimaryController`, misalkan `updateView(Mahasiswa m)` untuk mengupdate tampilan layar berdasarkan `m`
3. Di awal program, cukup `this.updateView(mahasiswaList[0])`
4. Saat mendapatkan data mahasiswa berikutnya, `this.updateView(listMahasiswa[this.getIndexOfMahasiswa()])`

Jadi bagian mengupdate tampilannya jangan duplikat.

**Comment by harrysenjaya** [comment]
Sudah diimplementasikan dan sudah dipush.
